- name: Setup nginx on remote machine
  hosts: azure_keycloak
  gather_facts: false
  tasks:
    - name: Create folders for buliding
      ansible.builtin.file:
        path: /home/keycloakuser/{{ item }}
        state: directory
        mode: '0755'
        #path: /home/keycloakuser/ansible-hylastix/ngnix
        #state: directory
        #mode: '0755'
      loop:
        - ansible-hylastix
        - ansible-hylastix/ngnix
    - name: Copy files to nginx folder
      ansible.builtin.copy:
        src: ../ansible/nginx/{{ item }}
        dest: /home/keycloakuser/ansible-hylastix/ngnix/{{ item }}
        #owner: kunalagon
        #group: kunalagon
        #mode: '0644'
      loop:
        - docker-compose.yml
        - nginx.conf
        - Dockerfile

    - name: Build and start nginx custom container
      become: true
      community.docker.docker_compose_v2:
        project_src: /home/keycloakuser/ansible-hylastix/ngnix/
        recreate: always
        files:
          - docker-compose.yml
