name: 'Deploy Keycloak and Nginx'
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy Ansible Playbook
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory:  ./ansible
    #environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          echo "${{ secrets.KEYCLOAK_VM_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible NGINX Deploy
        env:
          ANSIBLE_USER: ${{ secrets.AZURE_VM_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i hosts.ini nginx_setup.yml --private-key private_key.pem -u ${{ secrets.KEYCLOAK_VM_AZURE_USER }}

      - name: Run Ansible KEYCLAOK Deploy
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i hosts.ini keycloak.yml --private-key private_key.pem -u ${{ secrets.KEYCLOAK_VM_AZURE_USER }}    
      
